[mypy]
python_version = 3.12
files = src
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
strict_optional = True
no_implicit_optional = True
disallow_untyped_defs = True
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True
