class DBManager:
    """DBManager (заглушка — методы добавлю после наполнения БД)."""
    def __init__(self) -> None:
        pass

    # def get_companies_and_vacancies_count(self): ...
    # def get_all_vacancies(self): ...
    # def get_avg_salary(self): ...
    # def get_vacancies_with_higher_salary(self): ...
    # def get_vacancies_with_keyword(self, keyword: str): ...
